# Generated by Django 4.0.4 on 2022-05-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_company_options_alter_house_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
